version: '2'
services:
  mongodb:
    image: mongo:3.0
    command: --smallfiles
    ports: ["27017:27017"]
    volumes: ["/data/db:/data/db"]
  hanhttpserver:
    # environment:
      # - SLACK_API_TOKEN=
    build:
      context: .
      dockerfile: hanhttpserver/Dockerfile
    ports: ["80:80"]
    links: ['mongodb']
    command: hanhttpserver
  # hancollector:
  #   # environment:
  #     # - SLACK_API_TOKEN=
  #   build:
  #     context: .
  #     dockerfile: hancollector/Dockerfile
  #   links: ['mongodb']
  #   command: hancollector
